<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.8"/>
        <PackageReference Include="MudBlazor" Version="9.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\Services.Abstractions\Services.Abstractions.csproj"/>
        <ProjectReference Include="..\Services\Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Components\BoardColumn\BoardColumn.razor" />
        <AdditionalFiles Include="Components\BoardExportControls\BoardExportControls.razor" />
        <AdditionalFiles Include="Components\TaskAttachment\TaskAttachment.razor" />
        <AdditionalFiles Include="Components\TaskCard\TaskCard.razor" />
        <AdditionalFiles Include="Components\TaskComments\TaskComments.razor" />
        <AdditionalFiles Include="Pages\Home\Home.razor"/>
        <AdditionalFiles Include="Pages\Shared\NotFound.razor"/>
    </ItemGroup>

</Project>
